import pandas as pd

# Datos extraídos de la imagen
data = {
    "COMERCIO": ["ALIMENTOS PEDREGAL", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "ALVI", "APPIO GOURMET", "BENAT"],
    "DIRECCIÓN": ["VITACURA 7648", "DOMINGO SANTA MARIA 3897", "TENIENTE CRUZ 570", "21 DE MAYO 1081", "LAS CONDES 11097", "SAN PABLO 5660", "PAJARITOS 5100", "SAN MARTIN 30", "PAJARITOS 1637", "CONCHA Y TORO 3088", "JOSE MIGUEL CARRERA 13059", "INDEPENDENCIA 4154", "JJ PEREZ 6658", "SANTA ROSA 9267", "SANTA ROSA 13218", "SANTA ROSA 5780", "RECOLETA 1750", "CAUPOLOICAN 1340", "SAN PABLO 8685 LOCAL SAN PABLO", "EYZAGUIRRE 2909", "MONTEVIDEO 527, LOCAL 527, RECOLETA", "TOBALABA 1445 PISO 1"],
    "COMUNA": ["VITACURA", "RENCA", "PUDAHUEL", "TALAGANTE", "LAS CONDES", "QUINTA NORMAL", "MAIPU", "QUILICURA", "MAIPU", "PUENTE ALTO", "EL BOSQUE", "INDEPENDENCIA", "CERRO NAVIA", "SAN RAMON", "LA PINTANA", "SAN JOAQUIN", "RECOLETA", "RENCA", "PUDAHUEL", "PUENTE ALTO", "RECOLETA", "PROVIDENCIA"],
    "CIUDAD": ["VITACURA", "SANTIAGO", "PUDAHUEL", "TALAGANTE", "LAS CONDES", "QUINTA NORMAL", "MAIPU", "QUILICURA", "MAIPU", "PUENTE ALTO", "EL BOSQUE", "INDEPENDENCIA", "CERRO NAVIA", "SAN RAMON", "LA PINTANA", "SAN JOAQUIN", "RECOLETA", "RENCA", "PUDAHUEL", "PUENTE ALTO", "RECOLETA", "PROVIDENCIA"],
    "TIPO DE ESTABLECIMIENTO": ["SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "PUNTO NATURAL", "PUNTO NATURAL"]
}

# Crear DataFrame
df = pd.DataFrame(data)

# Datos extraídos de la segunda imagen
data = {
    "COMERCIO": [
        "BERRY NATURAL SPA", "CANASTA RAICES SANAS", "CHILE SIN GLUTEN", "Comercial Piwën SpA", 
        "Comercial Piwën SpA", "Comercial Piwën SpA", "Comercial Piwën SpA", "CONFITERIA SAZIE", 
        "CUGAT", "DULCE POLA", "Ecotienda PEWEN", "EL BODEGUERO", "ERBI", "ERBI", "ERBI", 
        "ERBI", "ERBI", "ERBI", "ERBI", "ERBI", "ERBI", "ERBI", "ERBI", "ERBI", "ERBI", 
        "ERBI", "ERBI"
    ],
    "DIRECCIÓN": [
        "AV PEDRO FONTOAVA 7855, LOCAL FV 11", "CONDELL 1137", "LO OVALLE 494", "SERAFIN ZAMORA 49", 
        "LARRAIN 5862 MP 1511", "CONDELL 1368", "CONDELL 1368", "SAZIE 2253", "MAIPU 806", 
        "DEL VALLE SUR 512 LOC 102", "SUCRE 431 LOC 2", "IRARRAZABAL 1816", "BAJOS DE SAN AGUSTIN 0 LOC 5", 
        "LOS BAJOS DE SAN AGUSTIN 0 LOC 5", "SANTA ROSA 79 LOC 81", "VICUÑA MACKENA 3011", 
        "GRAN AVENIDA 6279", "ELIODORO YAÑEZ 1103", "MERCED 711 LOC 40", "LAS PERDICES 2990 LOC 40", 
        "MIGUEL CAMPINO 245", "LOS ESTUDIANTES 8145", "GERONIMO DE ALDERETE 1622", "SANTA ROSA 905", 
        "QUIAPO 3055", "SAN JUAN 7209", "EL AGUILUCHO 3420"
    ],
    "COMUNA": [
        "HUECHURABA", "PROVIDENCIA", "QUILICURA", "LA FLORIDA", "LA REINA", "PROVIDENCIA", "PROVIDENCIA", 
        "SANTIAGO", "BUIN", "HUECHURABA", "NUÑOA", "NUÑOA", "CALERA DE TANGO", "MELIPILLA", 
        "SANTIAGO", "SAN JOAQUIN", "SAN MIGUEL", "PROVIDENCIA", "MELIPILLA", "PEÑALOLEN", "PAINE", 
        "CERRILLOS", "LA FLORIDA", "SANTIAGO", "PEDRO AGUIRRE CERDA", "CERRILLOS", "PROVIDENCIA"
    ],
    "CIUDAD": [
        "HUECHURABA", "SANTIAGO", "QUILICURA", "SANTIAGO", "SANTIAGO", "SANTIAGO", "SANTIAGO", 
        "SANTIAGO", "BUIN", "SANTIAGO", "SANTIAGO", "SANTIAGO", "CALERA DE TANGO", "CALERA DE TANGO", 
        "SANTIAGO", "SAN JOAQUIN", "SAN MIGUEL", "PROVIDENCIA", "MELIPILLA", "PEÑALOLEN", "PAINE", 
        "CERRILLOS", "LA FLORIDA", "SANTIAGO", "PEDRO AGUIRRE CERDA", "CERRILLOS", "PROVIDENCIA"
    ],
    "TIPO DE ESTABLECIMIENTO": [
        "PUNTO NATURAL", "PUNTO NATURAL", "PUNTO NATURAL", "PUNTO NATURAL", "PUNTO NATURAL", 
        "PUNTO NATURAL", "PUNTO NATURAL", "PUNTO NATURAL", "SUPERMERCADOS", "PUNTO VERDE", 
        "PUNTO NATURAL", "PUNTO NATURAL", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", 
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", 
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", 
        "SUPERMERCADOS", "SUPERMERCADOS"
    ]
}

# Crear DataFrame
df_new = pd.DataFrame(data)

# Guardar en un archivo CSV
csv_path = 'region_metropolitana_santiago_extended.csv'
# Combinar con el primer DataFrame y guardar
df_combined = pd.concat([df, df_new], ignore_index=True)

# Datos extraídos de la tercera imagen
data = {
    "COMERCIO": [
        "ERBI", "ERBI", "ERBI", "ERBI", "ERBI", "ERBI", "ERBI", 
        "FLORIDA NATURALS - ASUR", "FRESH EXPRESS", "JUMBO - 'Mundo Bionatura'", 
        "JUMBO - 'Mundo Bionatura'", "JUMBO - 'Mundo Bionatura'", 
        "JUMBO - 'Mundo Bionatura'", "JUMBO - 'Mundo Bionatura'", 
        "JUMBO - 'Mundo Bionatura'"
    ],
    "DIRECCIÓN": [
        "SAN DIEGO 936", "GRAN AVENIDA 4293", "PORTUGAL 472", "GRAN AVENIDA 5783", 
        "DIEGO PORTALES 4290", "GRAN AVENIDA 8101", "AMBROSIO O'HIGGINS 1595", 
        "EL ROBLE 970", "GENERAL JOFRE 214 LOC 6", "PIE ANDINO 4770 LOCAL J958", 
        "SANCHEZ FONTECILLA 12000", "JOSE PEDRO ALESSANDRI 1166", 
        "AMERICO VESPUCIO 1001", "VICUÑA MACKENNA 6100", "EL LLANO SUBERCASEAUX 3519"
    ],
    "COMUNA": [
        "SANTIAGO", "LA CISTERNA", "SANTIAGO", "LA CISTERNA", "SAN BERNARDO", 
        "LA CISTERNA", "CURACAVI", "LAMPA", "SANTIAGO", "LA DEHESA", "PEÑALOLEN", 
        "NUÑOA", "MAIPU", "LA FLORIDA", "SAN MIGUEL"
    ],
    "CIUDAD": [
        "SANTIAGO", "LA CISTERNA", "SANTIAGO", "LA CISTERNA", "SAN BERNARDO", 
        "LA CISTERNA", "CURACAVI", "LAMPA", "SANTIAGO", "LA DEHESA", "PEÑALOLEN", 
        "NUÑOA", "MAIPU", "LA FLORIDA", "SAN MIGUEL"
    ],
    "TIPO DE ESTABLECIMIENTO": [
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", 
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "PUNTO NATURAL", 
        "PUNTO NATURAL", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", 
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS"
    ]
}

# Crear DataFrame
df_new = pd.DataFrame(data)
# Combinar con los DataFrames anteriores y guardar
df_combined_v2 = pd.concat([df_combined, df_new], ignore_index=True)


# Datos extraídos de la quinta imagen
data = {
    "COMERCIO": [
        "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", 
        "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", 
        "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10"
    ],
    "DIRECCIÓN": [
        "SAN MARTIN 460", "GABRIELA ORIENTE 0651", "MARATHON 3123", "SANTA ROSA 7592", 
        "ROJAS MAGALLANES 1856", "CAMILO HENRIQUEZ 5239", "AMERICO VESPUCIO 1601", 
        "GLADYS MARIN 6664", "VICUÑA MACKENNA 7320", "BULNES 550", "EL SALTO 2506", 
        "2 NORTE 1373", "LLICO 456", "SAN PABLO 8537"
    ],
    "COMUNA": [
        "SAN BERNARDO", "PUENTE ALTO", "MACUL", "LA GRANJA", "LA FLORIDA", "PUENTE ALTO", 
        "CERRILLOS", "ESTACION CENTRAL", "LA FLORIDA", "SAN BERNARDO", "RECOLETA", "MAIPU", 
        "SAN JOAQUIN", "PUDAHUEL"
    ],
    "CIUDAD": [
        "SAN BERNARDO", "PUENTE ALTO", "MACUL", "LA GRANJA", "LA FLORIDA", "PUENTE ALTO", 
        "CERRILLOS", "ESTACION CENTRAL", "LA FLORIDA", "SAN BERNARDO", "RECOLETA", "MAIPU", 
        "SAN JOAQUIN", "PUDAHUEL"
    ],
    "TIPO DE ESTABLECIMIENTO": [
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", 
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", 
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS"
    ]
}

# Crear DataFrame
df_new = pd.DataFrame(data)

# Guardar en un archivo CSV
csv_path = 'region_metropolitana_santiago_extended_v3.csv'

# Combinar con los DataFrames anteriores y guardar
df_combined_v3 = pd.concat([df_combined_v2, df_new], ignore_index=True)
df_combined_v3.to_csv(csv_path, index=False)



import pandas as pd

# Datos extraídos de la sexta imagen
data = {
    "COMERCIO": [
        "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", 
        "MAYORISTA 10", "MAYORISTA 10", "MAYORISTA 10", "NATURAL SELF", "NUTTYNUTS HUERFANOS", 
        "PASAS Y PERAS", "PIWËN FRUTOS SECOS", "PLANTA MAESTRA", "PLANTA MAESTRA", 
        "PLANTA MAESTRA", "PLANTA MAESTRA", "S10", "S10", "S10 Gran Avenida", 
        "SANTA ISABEL - 'Libres de'", "SANTA ISABEL - 'Libres de'", "SANTA ISABEL - 'Libres de'", 
        "SANTA ISABEL - 'Libres de'", "SANTA ISABEL - 'Libres de'", "SANTA ISABEL - 'Libres de'", 
        "SANTA ISABEL - 'Libres de'"
    ],
    "DIRECCIÓN": [
        "CARRETERA GENERAL SAN MARTIN 381", "SAN JOSE DE LA ESTRELLA 1392", "SAN PABLO 6702", 
        "21 DE MAYO 4287", "MANUEL RODRIGUEZ 312", "GRAN AVENIDA 9150", "PORTALES 2448 ESQUINA GRAL URRUTIA", 
        "GLADYS MARIN 6480 PISO ESTACION CENTRAL", "PASAJE TEJA FLAMENCA 4760", "HUERFANOS 801", 
        "PORTUGAL 56 LOC 7", "APOQUINDO 4411 LOC S8A", "IRARRAZAVAL 3661 LOC 1", "MANUEL MONTT 187 LOC 3", 
        "MERCED 295 - C", "HOLANDA 069", "PORTALES ORIENTE 1701", "DIAGONAL TENIENTE CRUZ 530", 
        "GRAN AVENIDA 6060", "VIRGINIA SUBERCASEAUX 447 LOCAL 6", "ORIENTE AUTOPISTA LOS LIBERTADORES 22909 LOCAL 14", 
        "VICUÑA MACKENNA 202", "EL GABINO 5830 LOCAL 2", "CONSISTORIAL 2100", "ALMIRANTE RIVERO 2105", 
        "LIBERTADOR BERNARDO O'HIGGINS 2001 LOCAL COMERCIAL 100"
    ],
    "COMUNA": [
        "COLINA", "LA FLORIDA", "LO PRADO", "PEÑAFLOR", "BUIN", "LA CISTERNA", "SAN BERNARDO", 
        "ESTACION CENTRAL", "PEÑALOLEN", "SANTIAGO", "SANTIAGO", "LAS CONDES", "NUÑOA", 
        "PROVIDENCIA", "SANTIAGO", "PROVIDENCIA", "SAN BERNARDO", "PUDAHUEL", "SAN MIGUEL", 
        "PIRQUE", "COLINA", "MELIPILLA", "LO BARNECHEA", "PEÑALOLEN", "SAN BERNARDO", "TALAGANTE"
    ],
    "CIUDAD": [
        "COLINA", "LA FLORIDA", "LO PRADO", "PEÑAFLOR", "BUIN", "LA CISTERNA", "SAN BERNARDO", 
        "ESTACION CENTRAL", "PEÑALOLEN", "SANTIAGO", "SANTIAGO", "LAS CONDES", "SANTIAGO", 
        "PROVIDENCIA", "SANTIAGO", "PROVIDENCIA", "SAN BERNARDO", "PUDAHUEL", "SAN MIGUEL", 
        "PIRQUE", "COLINA", "MELIPILLA", "LO BARNECHEA", "PEÑALOLEN", "SAN BERNARDO", "TALAGANTE"
    ],
    "TIPO DE ESTABLECIMIENTO": [
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", 
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "PUNTO NATURAL", "PUNTO NATURAL", 
        "PUNTO VERDE", "PUNTO NATURAL", "PUNTO VERDE", "PUNTO VERDE", "PUNTO VERDE", "PUNTO VERDE", 
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", 
        "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS", "SUPERMERCADOS"
    ]
}

# Crear DataFrame
df_new = pd.DataFrame(data)

# Guardar en un archivo CSV
csv_path = 'region_metropolitana_santiago_extended_v4.csv'

# Combinar con los DataFrames anteriores y guardar
df_combined_v4 = pd.concat([df_combined_v3, df_new], ignore_index=True)
df_combined_v4.to_csv(csv_path, index=False)

csv_path


