name: Deploy to Render

on:
  push:
    branches:
      - main  # Ajusta la rama si necesitas desplegar desde otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Ajusta la versión de Node.js según tus necesidades

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build  # Ajusta el comando de construcción si es necesario

    - name: Deploy to Render
      env:
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}  # Agrega este secreto en tu repositorio
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}        # Agrega este secreto en tu repositorio
      run: |
        curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{}' \
          https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
